Assassin Info + Fix KW info
McTsts/Werewolves-Roles pull request #1292
Opened 2023-12-12 21:51 UTC by Shepherdwhen

2023-12-12 21:58 UTC, McTsts requested changes
wait until emoji

2023-12-13 21:45 UTC, rupertandrosy commented
does not need my review. consider mentioning "knives" in the assassin desciption

2023-12-16 14:48 UTC, venomousbirds approved these changes
Emoji added

2023-12-16 15:56 UTC, McTsts approved these changes

2023-12-16 16:11 UTC, merged