Create occult wolf
McTsts/Werewolves-Roles pull request #1293
Opened 2023-12-12 22:08 UTC by Shepherdwhen

2023-12-12 23:41 UTC, McTsts approved these changes

2023-12-13 21:46 UTC, rupertandrosy commented
i don't like the name. occult has a completely different meaning to cultist. it should just be cultist wolf

2023-12-13 21:52 UTC, rupertandrosy requested changes
would like the name changed to cultist wolf (or similar), and the files changed accordingly

2023-12-14 11:06 UTC, Shepherdwhen commented
@rupertandrosy done

@McTsts conflicts :)

2023-12-14 15:25 UTC, merged