Remove new TI from baroness roles
McTsts/Werewolves-Roles pull request #1296
Opened 2023-12-13 12:16 UTC by Shepherdwhen

2023-12-13 20:50 UTC, McTsts requested changes
Tanner is once again WP

2023-12-13 22:09 UTC, rupertandrosy commented
i maintain that it would be easier if baroness had no special roles, but i have nothing specific to review here

2023-12-14 10:50 UTC, Shepherdwhen commented
> Tanner is once again WP

@McTsts Done

2023-12-14 15:35 UTC, McTsts approved these changes

2023-12-14 15:35 UTC, merged