Update macho
McTsts/Werewolves-Roles pull request #145
Opened 2021-04-19 10:22 UTC by venomousbirds

not sure how to word it

2021-04-19 10:22 UTC, venomousbirds commented
should fix #144

2021-04-19 10:37 UTC, McTsts requested changes
sounds pretty confusing

2021-04-19 10:38 UTC, McTsts commented
I don't think the "won't survive" thing needs clarification probably?

2021-04-20 12:00 UTC, McTsts approved these changes

2021-04-20 12:01 UTC, merged